{% set name = "pylibjpeg" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylibjpeg-{{ version }}.tar.gz
  sha256: 3beae5cf829f83bf0c1e5640c3b655bc0f406b8be302215e72f8d31a4185a947

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - pylibjpeg
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python framework for decoding JPEG and decoding/encoding DICOM RLE data, with a focus on supporting pydicom
  license: MIT
  license_file: LICENCE.txt
  home: https://github.com/pydicom/pylibjpeg

extra:
  recipe-maintainers:
    - dstansby
